version: "3.9"

services:
  redis:
    image: redis:7.2-alpine   # lightweight Redis image
    container_name: redis-laundrymart
    restart: unless-stopped
    ports:
      - "6378:6379"           # expose Redis to host
    volumes:
      - redis_data:/data      # persist data

volumes:
  redis_data:
